name: 'Quant Cloud ECR Login'
description: 'Get ECR login credentials from Quant Cloud'
icon: 'archive'
color: 'purple'
inputs:
  api_key:
    description: 'Quant Cloud API key'
    required: true
  organization:
    description: 'Quant Cloud organisation name'
    required: true
  base_url:
    description: 'Quant Cloud API base URL'
    required: false
outputs:
  username:
    description: 'ECR username'
  password:
    description: 'ECR password'
  endpoint:
    description: 'ECR endpoint'
runs:
  using: 'node20'
  main: 'dist/index.js' 