name: Test ECR Login

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/test.yml'
      - 'package.json'
      - 'package-lock.json'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build with ncc
        run: npx ncc build src/index.ts

      - name: Debug Action Files
        run: |
          ls -la
          ls -la dist/
          cat action.yml

      - name: Get ECR Credentials
        uses: ./
        id: ecr-login
        with:
          api_key: ${{ secrets.QUANT_API_KEY }}
          organization: 'quant'
          base_url: 'https://portal.stage.quantcdn.io/api/v3'

      - name: Debug Outputs
        run: |
          echo "Username: ${{ steps.ecr-login.outputs.username }}"
          echo "Endpoint: ${{ steps.ecr-login.outputs.endpoint }}"
          echo "Password is masked"

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.ecr-login.outputs.endpoint }}
          username: ${{ steps.ecr-login.outputs.username }}
          password: ${{ steps.ecr-login.outputs.password }}

      - name: Verify Login
        run: docker info 